language: node_js
node_js:
  - "node"
script:
  -
after_success:
  - npm install -g firebase-tools
  - firebase --non-interactive deploy --token "${FIREBASE_TOKEN}"
#deploy:
#  provider: firebase
#  token:
#    secure: "E6k9yNfyEM6qodvUas9FfcxdsaS4rmQgERmrElYJ2sUCHGDphKpfUc3X9IHds6rb6etMWlLAGZ82Vb6xbvZUJeSBMTyu9Kyy5/eBX1HH1Dm5W/i9izRw3MW+vf7IwQMi1EifrER67mA6K6tcXb8hvoTeXAXqeM9hWTcOn9Qe5+A5DB9S12LM7c8SVha5+2MlSW0Bhge/oBttcUsNLPmAG95CcAI4PRIw2bC4mfQHK/ONA0F/vczXYzPGIbAwt4xCmAIziaG9g2FgPNC4SCWNVwhqQOTUjoaLdVBTf6JW87RQDo6R1H2ZRd0Ufn6sHHMAALbaVuGM6AP4AbxGs1tmIOl2JmVhkzmlC/ysNwNDQvpgpgnalvxCtRWU3kuS/wLT9QsW71mbuOmUET32NHOG97Y352czRa9Q5GO5CcZm5C20xW4WjvPc7IzMd+PBByuqfLYWkBkz4yTvr3gOzLYbRTtLZqM7Bo6MRMkAnc0dp9uZS1aKBR7KznYHwW3kZMnQG6aVr02CH9Rpl1qmRiqPkdDK78sJbPWCF9s1oJpom6o8KOvFv88AVhfa7gGqSt0Fz0ZREemMrFaPJn6eyUQEQ2twcrWYM8gY/g2ZaJCay/h1Jhix5p+xZuLtSWC2sP6mns3Rz3Z6pzQB7o1xp9o2kXIeE1XAL5HPac2YhjK5tJk="
